// config/timing.js — UI 타이머/지연값 중앙 관리
// 도메인 규칙(Pomodoro 25/5분, 시험 1분/문항)은 이 파일에서 명명만 부여하고 보존.

export const TIMING = {
  // 교재 리더 프리뷰/참조
  PREVIEW_HOVER_MS: 400,
  PREVIEW_LONG_PRESS_MS: 600,
  PREVIEW_HIDE_MS: 3000,
  CROSS_REF_SCROLL_DELAY_MS: 800,
  AUDIO_STATUS_CLEAR_MS: 2500,

  // 시험 시뮬레이터
  EXAM_TIMER_TICK_MS: 500,
  EXAM_DRAFT_SAVE_INTERVAL_SEC: 5,
  EXAM_TIME_PER_QUESTION_SEC: 60,

  // 뽀모도로 (도메인 규칙)
  POMODORO_TICK_MS: 200,
  POMODORO_WORK_SEC: 25 * 60,
  POMODORO_BREAK_SEC: 5 * 60,

  // 차트 툴팁
  CHART_TOOLTIP_HIDE_MS: 100,
  CHART_TOOLTIP_TOUCH_HIDE_MS: 2000,

  // 검색
  SEARCH_DEBOUNCE_MS: 250,

  // PWA / SW
  PWA_RELOAD_DELAY_MS: 600,
  PWA_TOAST_HIDE_MS: 5000,
  PWA_PROBE_TIMEOUT_MS: 8000,
  PWA_WAKE_GRACE_MS: 15000,

  // 데이터 로더
  SCRIPT_RETRY_DELAY_MS: 100,

  // 제스처
  SWIPE_THRESHOLD_PX: 50,
  SWIPE_TIME_MAX_MS: 500,
};
